#!/bin/sh
if command -v podman; then
    CONTAINER_ENGINE=podman
else
    CONTAINER_ENGINE=docker
fi

$CONTAINER_ENGINE compose build && \
$CONTAINER_ENGINE compose run --rm --service-ports build "$@"